swagger: "2.0"
info:
  title: Bank Argent-Transactions API
  description: API allowing users to manage their transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Route pour récupérer tous les comptes d'un utilisateur
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Retrieve all user accounts with transactions
      description: Fetches all accounts and their transactions for the current user
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transaction list
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Accounts not found
        "500":
          description: Internal Server Error
  # Route pour récupérer un compte
  /user/accounts/{idAccount}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Retrieve a user account by its ID
      description: Fetches a specific user account by its unique ID and returns associated transaction data.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idAccount
          description: Unique identifier of the account to be retrieved.
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transaction
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Accounts not found
        "500":
          description: Internal Server Error
  #  Route pour récupérer des transactions sur les 3 derniers mois
  /transactions/{account}/{idTransaction}/{startDate}/{endDate}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve all transactions for the last 3 months
      description: Fetch all transactions for the last 3 months, grouped by account
      parameters:
        - in: path
          name: account
          description: Account ID
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Transaction ID
          required: true
          type: string
        - in: path
          name: startDate
          description: Start date for filtering transactions (3 months ago)
          required: true
          type: string
          format: date
        - in: path
          name: endDate
          description: End date for filtering transactions (today)
          required: true
          type: string
          format: date
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transactions for the last 3 months
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  # Route pour récupérer une transaction spécifique
  /transactions/{account}/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve a specific transaction by ID
      description: Fetch details of a transaction by account ID and transaction ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: account
          description: Account ID
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update a transaction
      description: Modify a transaction's category and notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction category and notes
          required: true
          schema:
            $ref: "#/definitions/ModifyTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
      amount:
        type: number
      date:
        type: string
        format: date
      type:
        type: string
      description:
        type: string
  ModifyTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
