swagger: "2.0"
info:
  title: Bank Argent-Transactions API
  description: API allowing users to manage their transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Route pour récupérer tous les comptes d'un utilisateur
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Retrieve all user accounts
      description: Fetches all accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transaction list
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Accounts not found
        "500":
          description: Internal Server Error
  # Route pour récupérer un compte spécifique
  /accounts/{idAccount}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Retrieve a user account by its ID
      description: Fetches a specific user account by its unique ID.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idAccount
          description: Unique identifier of the account to be retrieved.
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transaction
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "404":
          description: Accounts not found
        "500":
          description: Internal Server Error
  #  Route pour récupérer des transactions pour le mois en cours
  /transactions/{account}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve all transactions for the current month
      description: Fetch all transactions for the current month, grouped by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: account
          description: Account ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved transactions for the current month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  # Route pour récupérer une transaction spécifique
  /transactions/transaction/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Retrieve a specific transaction by ID
      description: Fetch details of a transaction by account ID and transaction ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    # Route pour modifier la categorie et les notes d'une transaction
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update a transaction
      description: Modify a transaction's category and notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction category and notes
          required: true
          schema:
            $ref: "#/definitions/ModifyTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Account:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      amount:
        type: number
        format: float
      description:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      amount:
        type: number
        format: float
      date:
        type: string
        format: date
      type:
        type: string
      description:
        type: string
      category:
        type: string
      notes:
        type: string
      balance:
        type: string
        format: float
  ModifyTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
